tests/test_lbh15_fromX.py
Done the modifications in the test_lbh15_fromX.py file, related to the issue #31
=> Merge testfromX into the master  

lbh15/properties/interface.py
=> [53_info_improvement], issue - #53, Style improvement to info method

lbh15/_lbh15.py
Desired improvements done without changing the doc.
=> 57 load prop improvement

lbh15/_decorators.py, lbh15/properties/bismuth_thermochemical_properties/bismuth_thermochemical.py, lbh15/properties/interface.py, lbh15/properties/lbe_thermochemical_properties/lbe_oxygen_limits.py, lbh15/properties/lbe_thermochemical_properties/lbe_thermochemical.py, lbh15/properties/lead_thermochemical_properties/lead_oxygen_limits.py, lbh15/properties/lead_thermochemical_properties/lead_thermochemical.py, tests/test_lbh15_fromX.py
This pull request involves not only issue #31, but even issues #49 and #83, that should be closed.
=> 31 test from x

lbh15/_lbh15.py, lbh15/properties/lead_thermochemical_properties/lead_thermochemical.py
Simplified the custom properties dict
=> 58 custom prop modification

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
Addition of `_available_properties_dict` attribute and change of the retrieval of the available correlations.
=> Insertion of protected attribute storing all available properties

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
=> __Fill_instance_properties method improvement

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
Simplified the implementation of `__add_property()` method.
=> 63 add property improvement

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
Applied all the suggested modifications.
=> 64 check properties improvement

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
=> 65 fill class attr improvement

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
=> 67 compute t improvement

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
Modifications applied even to `__assign_T()` method.
=> 68 assign p improvement

lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py
Fulfilled all tasks by adding 3 if statements to warn the user about any abnormal behavior.
=> 69 change corr improvement

lbh15/_commons.py, lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py, lbh15/properties/bismuth_properties.py, lbh15/properties/lbe_properties.py, lbh15/properties/lead_properties.py
=> 71 constants commons

lbh15/_commons.py, lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py, lbh15/properties/bismuth_properties.py, lbh15/properties/bismuth_thermochemical_properties/bismuth_thermochemical.py, lbh15/properties/bismuth_thermochemical_properties/diffusivity_in_bismuth.py, lbh15/properties/bismuth_thermochemical_properties/solubility_in_bismuth.py, lbh15/properties/lbe_properties.py, lbh15/properties/lbe_thermochemical_properties/diffusivity_in_lbe.py, lbh15/properties/lbe_thermochemical_properties/lbe_oxygen_limits.py, lbh15/properties/lbe_thermochemical_properties/lbe_thermochemical.py, lbh15/properties/lbe_thermochemical_properties/solubility_in_lbe.py, lbh15/properties/lead_properties.py, lbh15/properties/lead_thermochemical_properties/diffusivity_in_lead.py, lbh15/properties/lead_thermochemical_properties/lead_oxygen_limits.py, lbh15/properties/lead_thermochemical_properties/lead_thermochemical.py, lbh15/properties/lead_thermochemical_properties/solubility_in_lead.py, tests/properties_bounds.json
=> 76 thermochemical review

lbh15/_commons.py, lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py, lbh15/properties/bismuth_properties.py, lbh15/properties/bismuth_thermochemical_properties/bismuth_thermochemical.py, lbh15/properties/bismuth_thermochemical_properties/diffusivity_in_bismuth.py, lbh15/properties/bismuth_thermochemical_properties/solubility_in_bismuth.py, lbh15/properties/lbe_properties.py, lbh15/properties/lbe_thermochemical_properties/diffusivity_in_lbe.py, lbh15/properties/lbe_thermochemical_properties/lbe_oxygen_limits.py, lbh15/properties/lbe_thermochemical_properties/lbe_thermochemical.py, lbh15/properties/lbe_thermochemical_properties/solubility_in_lbe.py, lbh15/properties/lead_properties.py, lbh15/properties/lead_thermochemical_properties/diffusivity_in_lead.py, lbh15/properties/lead_thermochemical_properties/lead_oxygen_limits.py, lbh15/properties/lead_thermochemical_properties/lead_thermochemical.py, lbh15/properties/lead_thermochemical_properties/solubility_in_lead.py, tests/properties_bounds.json
In addition to horner's scheme-related modifications, some other little changes have been applied for efficiency and style purposes.
=> 100 horner scheme

lbh15/_commons.py, lbh15/_lbh15.py, lbh15/bismuth.py, lbh15/lbe.py, lbh15/lead.py, lbh15/properties/bismuth_properties.py, lbh15/properties/bismuth_thermochemical_properties/bismuth_thermochemical.py, lbh15/properties/bismuth_thermochemical_properties/diffusivity_in_bismuth.py, lbh15/properties/bismuth_thermochemical_properties/solubility_in_bismuth.py, lbh15/properties/lbe_properties.py, lbh15/properties/lbe_thermochemical_properties/diffusivity_in_lbe.py, lbh15/properties/lbe_thermochemical_properties/lbe_oxygen_limits.py, lbh15/properties/lbe_thermochemical_properties/lbe_thermochemical.py, lbh15/properties/lbe_thermochemical_properties/solubility_in_lbe.py, lbh15/properties/lead_properties.py, lbh15/properties/lead_thermochemical_properties/diffusivity_in_lead.py, lbh15/properties/lead_thermochemical_properties/lead_oxygen_limits.py, lbh15/properties/lead_thermochemical_properties/lead_thermochemical.py, lbh15/properties/lead_thermochemical_properties/solubility_in_lead.py, tests/properties_bounds.json
All properties correlations made element-wise.
=> 103 elemental corrs

README.rst, docs/source/readme_full.rst
Documentation changed as described in #73
=> [73_iaea_oncore], issue #73, added link to oncore site by iaea

lbh15/_lbh15.py, lbh15/properties/interface.py
=> 107 warns always

lbh15/_lbh15.py
Added the class method `available_corrs_for_property` and the related doc. No changes to doc and tests.
=> 136 single prop avail corrs

README.rst, docs/source/learn_more.rst, docs/source/readme_full.rst
Modified README file and documentation (introduction and beginning of tutorial).
=> Improvement statement of need

CODE_OF_CONDUCT.rst, CONTRIBUTIONS.rst, README.rst, docs/source/contacts.rst, docs/source/learn_more.rst, docs/source/readme_full.rst
In the main project folder, two files has been created, that is:
- `CONTRIBUTIONS.rst`
- `CODE_OF_CONDUCT.rst`
=> Added documentation about contribution

joss/paper.md
Applied modifications suggested by reviewer 2.
=> JOSS paper: modifications suggested by reviewer 2

joss/paper.md
Applied the modifications as suggested by the reviewer 2.
=> Applied minor modifications

docs/source/readme_full.rst
=> Removed pprint from doc

docs/source/bismuth.rst, docs/source/lbe.rst, docs/source/lead.rst
Documentation changed in the API Guide section.
=> Converted property names in monospace

docs/source/readme_full.rst
"Advanced Usage" section modified according to the indications of reviewer 1.
No need to modify tests.
=> Refactor of advanced usage section

docs/source/learn_more.rst, lbh15/properties/lead_thermochemical_properties/lead_oxygen_limits.py
=> Validity range section

lbh15/_lbh15.py
Replace non OS separator with OS one
=> Check separator

docs/source/bismuth.rst, docs/source/lbe.rst, docs/source/lbh15.bib, docs/source/lead.rst, docs/source/learn_more.rst, docs/source/readme_full.rst, docs/source/release_notes.rst
Modifications have been applied in accordance with what suggested by reviewer 1.
=> Modification of doc according to reviewer 1

joss/paper.md
=> Added authors' credit section

README.rst, docs/source/contacts.rst
Modified as in issue description
=> 181 joss tag

lbh15/__init__.py, lbh15/bismuth.py, lbh15/properties/bismuth_thermochemical_properties/bismuth_contamination.py
Implementation of the following correlations:
Polonium activity coefficient by Joy, 1963.
Iodine vapour pressure by Cubicciotti, 1959.
=> Addition of bismuth contamination properties
